ECT/urls.py
from django.urls import path

from . import views

app_name = 'ECT'
urlpatterns = [
    path('edit/<int:num>/', views.edit, name = 'edit'),
    path('create/', views.create, name = 'create'),
    path('<int:meeting_id>/', views.detail, name = 'detail'),
    path('', views.index, name='index'),
]

django_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ECT/', include('ECT.urls')),
    path('hello/', include('hello.urls')),
    path('admin/', admin.site.urls),
]

hello/urls.py
from django.urls import path

from . import views

app_name = 'hello'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

ECT/models.py
from django.db import models

# Create your models here.

class Meeting(models.Model):
    date = models.DateTimeField()
    def __str__(self):
        return str(self.date.date())

class Topic(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    topic_text = models.CharField(max_length=200)
    def __str__(self):
        return self.topic_text

class Expression(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    expression_text = models.CharField(max_length=200)
    def __str__(self):
        return self.expression_text

class Member(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

cms/models.py
from django.db import models

# Create your models here.
class 

hello/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'    
class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
    

ECT/forms.py
from django import forms
from .models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name']

ECT/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Meeting, Member
from .forms import MemberForm
# Create your views here.
#class IndexView(generic.ListView):
def index(request):

    data = Member.objects.all()
    Meeting_list = Meeting.objects.order_by()
    context = {
        'Meeting_list' : Meeting_list,
        'data':data
        }
    return render(request, 'ECT/index.html', context)

def detail(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    return render(request, 'ECT/detail.html', {'meeting': meeting})

def create(request):

    if request.method =='POST':
        obj = Member()
        member = MemberForm(request.POST, instance = obj)
        member.save()
        return redirect(to='/ECT')
    
    params = {
        'title' : 'Ourteam members',
        'form': MemberForm(),
    }

    return render(request, 'ECT/create.html', params)

def edit(request, num):
    obj = Member.objects.get(id=num)
    if request.method=='POST':
        member = MemberForm(request.POST, instance=obj)
        member.save()
        return redirect(to='/ECT')
    params = {
        'title' :'Members',
        'id' : num,
        'form' : MemberForm(instance = obj),
    }
    return render(request, 'ECT/edit.html', params)

cms/views.py
from django.shortcuts import render

# Create your views here.

hello/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'hello/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be published in the future)."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'hello/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'hello/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'hello/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('hello:results', args=(question.id,)))

ECT/templates/ECT/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <table>
        <form action="{% url 'ECT:create' %}" method = "post">
            {% csrf_token %}
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" value = "click"></td></tr>
        </form>
    </table>
</body>
</html>

ECT/templates/ECT/detail.html
<h1>{{ meeting.date.date }}</h1>
<h2>Topics</h2>
<ul>
{% for topic in meeting.topic_set.all %}
    <li>{{ topic.topic_text }}</li>
{% endfor %}
</ul>
<h2>Expressions</h2>
<ul>
{% for expression in meeting.expression_set.all %}
    <li>{{ expression.expression_text }}</li>
{% endfor %}
</ul>

ECT/templates/ECT/edit.html
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <table>
        <form action="{%url 'ECT:edit' id %}" method="post">
            {% csrf_token %}
            {{ form.as_table}}
            <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
</body>

ECT/templates/ECT/index.html
<title>ECT homepage</title>
<head>English converstion over Zooooom!!</head>
<body>
<h1>Meeting list</h1>
{% if Meeting_list %}
    <ul>
    {% for meeting in Meeting_list %}
        <li><a href = "{% url 'ECT:detail' meeting.id %}">{{ meeting.date.date }}</a></li>
    {% endfor %}       
    </ul>
{% else %}
    <p>No meeting are scheduled.</p>
{% endif %}
</body>
<h1>Mebmbers</h1>
<table>
    <tr>
        <th>ID</th>
        <th>NAME</th>
    </tr>
    {% for item in data %}
    <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.name}}</td>
        <td><a href="{% url 'ECT:edit' item.id %}">Edit</a> </td>
    </tr>
    {% endfor %}
</table>
<p>If you want to register your name</p>
<li><a href = "{% url 'ECT:create' %}">{{ "please click here "}}</a></li>

hello/templates/hello/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hello:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

hello/templates/hello/index.html
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 18 20:25:31 2020

@author: yoshiki
"""

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'hello:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

hello/templates/hello/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'hello:detail' question.id %}">Vote again?</a>